Repository Vaibhavpratapsingh22/Courses, pull requests merged in 2020-09, with the labels that each got.

#62 Dbms mongo 2
  5-dbms/9-mongodb/2-data-model.md
  5-dbms/README.md
Labels: article

#64 Chapter 7 - Coaching
  7-scrum-master-role/7-coaching.md
  7-scrum-master-role/README.md
Labels: article

#63 Dbms mongo 3
  5-dbms/9-mongodb/3-collections.md
  5-dbms/README.md
Labels: article, implementation

#65 Dbms mongo 4
  5-dbms/9-mongodb/4-crud-operations.md
Labels: article, implementation

#66 Chapter 8 - Scrum Master Anti-Patterns
  7-scrum-master-role/8-anti-patterns.md
  7-scrum-master-role/README.md
Labels: article

#67 Dbms mongo 5
  5-dbms/9-mongodb/5-sharding.md
Labels: article

#68 Chapter 9 - Remote Work
  7-scrum-master-role/9-remote-work.md
  7-scrum-master-role/README.md
Labels: article

#70 Chapter 10 - Remote Toolkit
  7-scrum-master-role/01-scrum.md
  7-scrum-master-role/02-scrum-master.md
  7-scrum-master-role/03-facilitation.md
  7-scrum-master-role/04-team-building.md
  7-scrum-master-role/05-moderation.md
  7-scrum-master-role/06-teaching.md
  7-scrum-master-role/07-coaching.md
  7-scrum-master-role/08-anti-patterns.md
  7-scrum-master-role/09-remote-work.md
  7-scrum-master-role/10-remote-toolkit.md
  7-scrum-master-role/README.md
Labels: article

#74 Cn-introduction
  6-computer-networks/1-introduction.md
  6-computer-networks/README.md
Labels: article

#75 Cn basic concepts
  6-computer-networks/2-basic-concepts.md
  6-computer-networks/README.md
Labels: article

#77 transmission media
  6-computer-networks/3-osi-model.md
  6-computer-networks/4-transmission-media.md
  6-computer-networks/README.md
Labels: article

#78 Cn error detection correction
  6-computer-networks/5-error-detection-correction.md
  6-computer-networks/README.md
  ISSUE_TEMPLATE/adding-a-course.md
  ISSUE_TEMPLATE/bug_report.md
  ISSUE_TEMPLATE/feature_request.md
Labels: article

#80 Cn ip networking
  6-computer-networks/6-basic-ip-networking.md
  6-computer-networks/README.md
Labels: article, implementation

#82 Cn lan switching
  6-computer-networks/7-lan-switching.md
  6-computer-networks/README.md
Labels: article

#83 Created 1-introduction.md & README.md
  10-adobe-illustrator/1-introduction.md
  10-adobe-illustrator/README.md
Labels: article

#84 Cn ip addressing
  6-computer-networks/8-ip-addressing.md
  6-computer-networks/README.md
Labels: article, implementation

#85 Created 2-paletts.md & README.md
  10-adobe-illustrator/2-paletts.md
  10-adobe-illustrator/README.md
Labels: article

#87 Ai views
  10-adobe-illustrator/2-views.md
  10-adobe-illustrator/README.md
Labels: article

#88 Create 4-customizing.md & README.md
  10-adobe-illustrator/2-customizing.md
  10-adobe-illustrator/3-paletts.md
  10-adobe-illustrator/4-views.md
  10-adobe-illustrator/README.md
Labels: article

#90 Create 6-project.md
  10-adobe-illustrator/6-project.md
  10-adobe-illustrator/README.md
Labels: implementation

#92 created challenge-cn-nat.md & README.md
  6-computer-networks/README.md
  6-computer-networks/challenge-cn-nat.md
Labels: article, implementation
